### ISSUE TITLE
Could not find com.androidstudy:daraja:2.0.0.

### ISSUE THREAD

**Issue by joelkanyi** [jumaallan/android-daraja-sdk#75]
When adding the library to my `build.gradle` (Groovy) it says that it Could not find com.androidstudy:daraja:2.0.0. but when I use version `1.0.2` it work fine.

![Screenshot from 2022-06-09 05-44-24](https://user-images.githubusercontent.com/50293753/172753167-25133d1f-67a8-425f-b712-ae506d2ebe09.png)

**Comment by Daenjel** [comment]
Facing the same challenge on my end:

Failed to resolve: com.androidstudy:daraja:2.0.0

@jumaallan any assistance for this issue?

**Comment by jumaallan** [comment]
Hey @JoelKanyi / @Daenjel 

Thanks to @wangerekaharun , this should be fixed
